# Generated by Django 3.0.7 on 2020-09-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadelacompra', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeproducto', models.CharField(max_length=15)),
                ('producto', models.CharField(max_length=15)),
                ('cantidadXkilo', models.CharField(max_length=15)),
                ('precioXkilo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verduleria.Cliente')),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verduleria.Productos')),
            ],
        ),
    ]
