# Generated by Django 3.1.1 on 2020-09-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='factura',
            name='productocantidad',
            field=models.ManyToManyField(to='Verduleria.Producto'),
        ),
    ]
