# Generated by Django 3.0.7 on 2020-09-27 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dia',
        ),
        migrations.AddField(
            model_name='factura',
            name='fechadelacompra',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
