# Generated by Django 3.1.1 on 2020-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0002_auto_20200928_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidadXkilo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioXkilo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productocantidad',
            name='cantidad',
            field=models.SmallIntegerField(),
        ),
    ]
