# Generated by Django 3.1.1 on 2020-09-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0003_auto_20200930_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidadXkilo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipodeproducto',
            field=models.CharField(choices=[('1', 'Fruta'), ('2', 'Verdura')], max_length=1),
        ),
    ]
