# Generated by Django 3.1.1 on 2020-09-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0004_auto_20200930_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='productocantidad',
        ),
        migrations.AddField(
            model_name='productocantidad',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Verduleria.factura'),
            preserve_default=False,
        ),
    ]
