# Generated by Django 3.1.1 on 2020-09-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0005_auto_20200930_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumaTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verduleria.producto')),
            ],
        ),
    ]
