# Generated by Django 3.1.1 on 2020-10-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0007_factura_preciototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='preciototal',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
