# Generated by Django 3.1.1 on 2020-10-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0009_auto_20201001_0316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumaTotal',
        ),
    ]
