# Generated by Django 3.1.1 on 2020-10-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0011_auto_20201001_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioXkilo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
