# Generated by Django 3.1.1 on 2020-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verduleria', '0012_auto_20201001_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='preciototal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
